#!/bin/bash
set -eu

export PATH=/snap/bin:$PATH

mkdir -p "$CHARM_BUILD_DIR"

CHARM_SRC="$(realpath .)"

echo "Building net-attach-def-manager image..."
(cd net-attach-def-manager/; ./build)

echo "Building $CHARM..."
(cd "$CHARM_BUILD_DIR" && charmcraft build -f "$CHARM_SRC" 2>&1) | sed -e "s,in ',in '$CHARM_BUILD_DIR/,"
exit "${PIPESTATUS[0]}"
