#!/bin/bash
set -eu

if ! charm whoami > /dev/null; then
    echo "Not logged into charm store" 2>&1
    exit 1
fi
URL=$(charm push "$CHARM_BUILD_DIR/$CHARM.charm" "cs:~$NAMESPACE/$CHARM" | yq r - url)
echo "Uploaded: $URL"

MULTUS_IMAGE=$(yq r "metadata.yaml" "resources.multus-image.upstream-source")
docker pull "$MULTUS_IMAGE"
MULTUS_IMAGE_REV=$(charm attach cs:~"$NAMESPACE"/"$CHARM" --channel unpublished "multus-image=$MULTUS_IMAGE" | tail -n1 | sed -e 's/uploaded revision \([0-9]*\) of.*/\1/')
echo "Attached: multus-image-$MULTUS_IMAGE_REV"

NADF="net-attach-def-manager"
NADF_IMAGE_REV=$(charm attach cs:~"$NAMESPACE"/"$CHARM" --channel unpublished "$NADF-image=$NADF" | tail -n1 | sed -e 's/uploaded revision \([0-9]*\) of.*/\1/')
echo "Attached: $NADF-image-$NADF_IMAGE_REV"

if [ "$CHANNEL" != unpublished ]; then
    charm release "$URL" --channel "$CHANNEL" --resource "$NADF-image-$NADF_IMAGE_REV" --resource "multus-image-$MULTUS_IMAGE_REV"
    echo "Released to: $CHANNEL"
fi
